#!/bin/sh /etc/rc.common
#set -x

temp_file="/tmp/temp_usr.txt"
user_mtd=/dev/mtdblock6
magic_str=`hexdump -v -n 3 -e '1/1 "%02x"' $user_mtd`
magic=${magic_str:0:2}
usr_file="/etc/config/cgminer"
if [ $magic != "97" ]; then
	echo "no fl user name"
	user_pos=3;

	echo -n -e "\x97" > $temp_file
            dd if=$temp_file of=$user_mtd bs=1 count=1 seek=0

          	hex_data_str=`echo -n "$user_pos"| awk '{printf("%04x",$1)}'`
          	hex_data=`echo -n ${hex_data_str:0:2}`
          	echo -n -e "\x$hex_data" > $temp_file
          	hex_data=`echo -n ${hex_data_str:2:2}`
          	echo -n -e "\x$hex_data" >> $temp_file
            dd if=$temp_file of=$user_mtd bs=1 count=2 seek=1

	echo $_pooluser > $temp_file
            echo $_cgctrl >> $temp_file
	str_len=`cat $temp_file  | wc -c`
            dd if=$temp_file of=$user_mtd bs=1 count=$str_len seek=$user_pos
else
	user_pos=${magic_str:2:4}
	let user_pos=0x$user_pos
	user_pos=`echo $user_pos`
	dd of=$temp_file if=$user_mtd bs=1 count=100 skip=$user_pos
fi

fl_user=`sed -n '1p' $temp_file`
    echo $fl_user
    fl_cg_ctrl=`sed -n '2p' $temp_file`
if [ "$fl_user" != "$_pooluser" -o "$_cgctrl" != "$fl_cg_ctrl" ]; then
	if [ $_pooluser == "user" -a $_cgctrl == "en" ]; then
		sed -i "s#'${_pooluser}'#'${fl_user}'#g" $usr_file
		sed -i "s#${_cgctrl}#${fl_cg_ctrl}#g" $usr_file
		_pooluser=$fl_user
		_cgctrl=$fl_cg_ctrl
		echo "fl_user repalce config user"
	else
		echo "repalce fl user"
		usr_config_size=1024;
		fl_user_len=`echo $fl_user | wc -c`
		fl_cg_ctrl_len=`echo $fl_cg_ctrl | wc -c`
		user_pos=$(($user_pos+$fl_user_len+$fl_cg_ctrl_len))
		if [ `test $user_pos -ge $usr_config_size` ]; then
			user_pos=3
		fi
            	hex_data_str=`echo -n "$user_pos"| awk '{printf("%04x",$1)}'`
            	hex_data=`echo -n ${hex_data_str:0:2}`
            	echo -n -e "\x$hex_data" > $temp_file
            	hex_data=`echo -n ${hex_data_str:2:2}`
            	echo -n -e "\x$hex_data" >> $temp_file
            	hexdump $temp_file
            	dd if=$temp_file of=$user_mtd bs=1 count=2 seek=1
		echo $_pooluser > $temp_file
		echo $_cgctrl >> $temp_file
		str_len=`cat $temp_file  | wc -c`
		dd if=$temp_file of=$user_mtd bs=1 count=$str_len seek=$user_pos
	fi
	echo $_pooluser
	echo $_cgctrl
fi
